services:
  - type: web
    name: jaipur-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-uri
          property: connectionString
    healthCheckPath: /
